version: '3'
services:
    ieb_product_updater_service:
        container_name: ieb_product_updater_service
        env_file:
          - ".env"
          - ".rabbit.env"
        build: ./
        volumes:
          - ./:/ieb_product_updater
        ports:
          - '$MAP_PORT:$EXPOSE_PORT'
        restart: "always"
        networks:
          - app_net_s3
    rabbitmq_beat_service:
        build: ./
        volumes:
          - ./:/ieb_product_updater
        env_file:
          - ".env"
          - ".rabbit.env"
        command: "celery -A ieb_product_updater.celery.app beat -l info"
        restart: always

        depends_on:
          - rabbitmq_service
        networks:
          - app_net_s3
    rabbitmq_worker_service:
      build: ./
      volumes:
        - ./:/ieb_product_updater
      env_file:
        - ".env"
        - ".rabbit.env"
      command: "celery -A ieb_product_updater.celery.app worker -l info"
      restart: always
      depends_on:
        - rabbitmq_service
      networks:
        - app_net_s3
    rabbitmq_service:
        image: rabbitmq:3.11.11-alpine
        restart: always
        env_file:
          - ./.rabbit.env
        networks:
          - app_net_s3
volumes:
    .: null

networks:
    app_net_s3:
        name: app_net_s3
