# Generated by Django 4.1.7 on 2023-03-26 00:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "code",
                    models.TextField(
                        default=core.models.get_random_str,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Product ID",
                    ),
                ),
                (
                    "buying_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Buying Price"
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Selling Price"
                    ),
                ),
                ("description", models.TextField(verbose_name="Product Description")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Datetime"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updating Datetime"
                    ),
                ),
            ],
        ),
    ]
